### YamlMime:FAQ
metadata:
  title: Transport Layer Security Inspection Frequently Asked Questions   
  description: "Get answers to common questions about Transport Layer Security Inspection."
  author: HULKsmashGithub
  ms.author: jayrusso
  ms.service: global-secure-access
  ms.topic: faq   
  ms.date: 03/28/2025

title: Frequently asked questions for Transport Layer Security Inspection   
summary: |
  This article answers frequently asked questions about Transport Layer Security Inspection.   

sections:
  - name: Single section - ignored
    questions:
      - question: What is Transport Layer Security (TLS) Inspection? 
        answer: TLS Inspection involves decrypting and analyzing encrypted network traffic to detect threats, enforce security policies, and prevent data exfiltration. Given that most internet traffic is encrypted, inspecting this traffic is crucial for comprehensive security.
          
      - question: How does TLS Inspection work? 
        answer: TLS Inspection works by intercepting encrypted network traffic, decrypting it for security analysis, and then re-encrypting it before sending it to its destination. To implement this securely, organizations must define a TLS inspection policy, choose a trusted certificate authority for decryption, and deploy a trusted certificate to endpoints. This ensures seamless operation and prevents security warnings.   

      - question: What is certificate pinning, and how does it affect TLS inspection? 
        answer: Certificate pinning restricts an application's TLS connections to specific certificates, preventing interception but also blocking security solutions that rely on TLS inspection.   

      - question: How should we handle applications that use certificate pinning? 
        answer: The connection fails if MitM TLS inspection terminates traffic from applications that use certificate pining. To ensure your applications work as expected, create custom bypass rule in traffic forwarding profile to exclude traffic from these applications from Global Secure Access. We're working on TLS bypass to allow you to acquire traffic and apply security controls that don't rely on TLS inspection.

      - question: Is TLS 1.3 supported? 
        answer: Microsoft Entra supports TLS 1.3 end to end. By default, both TLS 1.2 and TLS 1.3 versions are enabled, with the highest mutually supported version selected for the session, from client to Global Secure Access and from Global Secure Access to the destinations. We don't support TLS 1.3 with Encrypted Client Hello (ECH) because the Server Name Indication (SNI) is encrypted, preventing Global Secure Access from creating the corresponding leaf certificates for TLS termination.

      - question: What happens if I have legacy applications using less secure TLS versions, such as TLS 1.1?
        answer: We recommend bypassing TLS Inspection for these destinations. TLS 1.2 is now the minimum recommended version, as older versions like TLS 1.1 and TLS 1.0 are considered insecure and vulnerable to attacks. Whenever possible, migrate these applications to support TLS 1.2 or higher.

      - question: Do you use hardware security modules (HSM) to protect keys?
        answer: We don't currently use hardware protection for key storage. However, keys are stored in memory only to dynamically generate leaf certificates for websites. While not protected by an HSM, access to our servers is highly restricted, and we implement stringent security controls to safeguard key access and system integrity.

      - question: What other Global Secure Access features have dependencies on TLS Inspection?
        answer: Content-based security controls have dependencies on TLS inspection, including URL-enhanced Web Category, anti-malware, DLP, ATP, and others.

additionalContent: |
    ## Related content

    * [Transport Layer Security Inspection Overview](concept-transport-layer-security.md)
    * [Configure Transport Layer Security](how-to-transport-layer-security.md)